# Generated by Django 4.2.7 on 2024-03-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
