# Generated by Django 4.2.7 on 2024-03-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtApp', '0002_alter_progress_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
