# Generated by Django 4.2.7 on 2024-03-07 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtApp', '0003_progress_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(max_length=200)),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtApp.blogs')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtApp.users')),
            ],
        ),
    ]
