# Generated by Django 4.2.7 on 2024-03-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtApp', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
