# Generated by Django 4.2.7 on 2024-03-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtApp', '0005_progress_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='img',
            field=models.URLField(null=True),
        ),
    ]
